#!/usr/bin/env python3
"""Stamp a spec-conformant companion config repo for promotion-assistant (config-spec E3/E4).

Mode B (secrets gitignored). Deterministic + template-driven: re-running with the same --out
produces byte-identical skeleton files, so two people generate the same structure (E4). Never
writes or echoes secrets.

This mirrors the schema documented in /CONFIG.md and reference/config-schema.md. It does NOT
recreate the config repo's scripts/apply.py — that is forked from companion config kit (the
benchmark mechanism), so init only leaves a pointer (avoids a conflicting second mechanism).

Discovery convention the skill uses (also in CONFIG.md, E2); first hit wins:
  1. $PROMO_CONFIG_DIR                        (primary, recommended)
  2. $PROMOTION_ASSISTANT_CONFIG             (config-spec canonical alias)
  3. $PROMOTION_ASSISTANT_CONFIG_DIR         (config-spec canonical alias)
  4. ~/.promotion-assistant-config/          (dotfile fallback)
  5. ~/.config/promotion-assistant-config/   (XDG fallback)

Usage:
  python init_config.py [--out <dir>] [--force]

--out   target config-repo dir; default is the dotfile path ~/.promotion-assistant-config/.
Stdlib only. Cross-platform.
"""
import argparse
import json
import os
import sys

PRIMARY_ENV = "PROMO_CONFIG_DIR"
DEFAULT_DIR = os.path.expanduser("~/.promotion-assistant-config")

# Mode B secrets gate for the COMPANION config repo (config-spec E6). Real values never enter git.
GITIGNORE = """\
# Secrets gate (config-spec E6 / Mode B) — real values never enter git.
secrets/*
!secrets/README.md
!secrets/.gitkeep
*.env
!*.env.template
!env.template
claude.json
.claude.json
*credentials*.json
*.key
*.pem
!*.key.template
!*.pem.template

# Runtime/PII state — gitignored per config-schema.md
metrics/
compliance/consent-ledger.jsonl
"""

SECRETS_README = """\
# secrets/ — Mode B (gitignored)

Per-channel credentials live here as `secrets/<slug>.env` and are **gitignored** (see ../.gitignore).
Promo OAuth/SMTP creds are high blast-radius and auto-revoked, so Mode B (never committed) is
mandatory — the market-intel "Mode A" rationale does not apply here.

Only `*.env.template` files and this README are committed. Back real values up out-of-band
(cloud sync / encrypted drive); restore on a new machine by copying the `*.env` files back, then
running `python scripts/verify_config.py` from the skill repo. Files MUST be UTF-8 without BOM.
"""

PRODUCT_JSON = {
    "schema_version": 1,
    "name": "<product-name>",
    "send_mode": "dry_run",
    "aff_base": "",
    "banned_claims": [],
    "compliance": {"physical_address": "", "unsubscribe_url": ""},
}

REGISTRY_JSON = {"schema_version": 1, "channels": []}

AUDIENCES_JSON = {"segments": {}}

APPLY_README = """\
# scripts/apply.py — fork it (do not hand-write)

`promotion-assistant apply` delegates to THIS file to bridge `secrets/<slug>.env` into the active
`~/.claude.json` (it must never echo secret values). It is intentionally NOT generated by
init_config.py so there is a single source of truth: **fork it from `companion config kit`'s
`scripts/apply.py`** and adapt the per-channel KEY=VALUE mapping. See ../runbooks/new-machine.md.
"""

RUNBOOKS = {
    "new-machine.md": "# New machine\n\n1. `git clone <your-private-config-repo> ~/.promotion-assistant-config`\n2. `export PROMO_CONFIG_DIR=~/.promotion-assistant-config` (or use the default path)\n3. Copy your out-of-band `secrets/*.env` back into `secrets/`.\n4. Fork `scripts/apply.py` from companion config kit; run `promotion-assistant apply`.\n5. From the skill repo: `python scripts/verify_config.py` (must report READY).\n",
    "live-authorize.md": "# Going live on a channel (irreversible outreach)\n\n1. Set `product.json.send_mode = \"live\"`.\n2. `export PROMO_LIVE_AUTHORIZED_<CHANNEL>=<any-non-empty-token>`.\n3. Ensure that channel's secrets are applied (`promotion-assistant apply`).\nUntil BOTH are present, dispatch simulates and writes metrics/dry-run.jsonl (zero egress).\n",
    "ban-recovery.md": "# Ban / throttle recovery\n\n1. Pause the channel (remove it from registry.json or set warmup_state to a cold tier).\n2. Inspect metrics/throttle-state.json and channels/<slug>/policy.json backoff (AIMD).\n3. Re-warm via the warmup_curve before re-enabling live.\n",
}


def write(path, content, force):
    if os.path.exists(path) and not force:
        print("  SKIP (exists): %s" % path)
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("  wrote: %s" % path)


def jdump(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Stamp a spec-conformant promotion-assistant config repo (Mode B).")
    ap.add_argument("--out", default=None, help="target config-repo dir (default ~/.promotion-assistant-config)")
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()

    out = os.path.abspath(os.path.expanduser(a.out or DEFAULT_DIR))
    print("Init promotion-assistant config repo (Mode B) at %s" % out)
    print("Discovery env var: %s  (aliases PROMOTION_ASSISTANT_CONFIG[_DIR]; fallback %s)"
          % (PRIMARY_ENV, DEFAULT_DIR))

    write(os.path.join(out, "product.json"), jdump(PRODUCT_JSON), a.force)
    write(os.path.join(out, "registry.json"), jdump(REGISTRY_JSON), a.force)
    write(os.path.join(out, "audiences.json"), jdump(AUDIENCES_JSON), a.force)
    write(os.path.join(out, ".gitignore"), GITIGNORE, a.force)
    write(os.path.join(out, "channels", ".gitkeep"), "", a.force)
    write(os.path.join(out, "copy", ".gitkeep"), "", a.force)
    write(os.path.join(out, "compliance", ".gitkeep"), "", a.force)
    write(os.path.join(out, "metrics", ".gitkeep"), "", a.force)
    write(os.path.join(out, "secrets", "README.md"), SECRETS_README, a.force)
    write(os.path.join(out, "secrets", ".gitkeep"), "", a.force)
    write(os.path.join(out, "scripts", "apply.README.md"), APPLY_README, a.force)
    for fn, body in RUNBOOKS.items():
        write(os.path.join(out, "runbooks", fn), body, a.force)

    print("\nNext:")
    print("  1) Fill product.json (name, aff_base, compliance.*) and add channels to registry.json.")
    print("  2) Per channel: channels/<slug>/policy.json (caps/gap/warmup/backoff) +")
    print("     secrets/<slug>.env (real values, gitignored) + secrets/<slug>.env.template.")
    print("  3) Fork scripts/apply.py from companion config kit (see scripts/apply.README.md).")
    print("  4) export %s=%s   (or use the default path)" % (PRIMARY_ENV, out))
    print("  5) python scripts/verify_config.py   # doctor: confirms the config is ready")
    return 0


if __name__ == "__main__":
    sys.exit(main())
